title = "lexffe.xyz"
description = "my little tech corner of the internet"
base_url = "https://lexffe.xyz"

compile_sass = false
build_search_index = false

minify_html = true
generate_feeds = true

[markdown]

render_emoji = true
github_alerts = true

[markdown.highlighting]
error_on_missing_language = true

style = "inline"
light_theme = "catppuccin-frappe"
dark_theme = "catppuccin-mocha"

[extra]
author = "lexffe"
github_url = "https://github.com/lexffe"
